package com.lemoulinstudio.small;

import java.util.Map;

/**
 * The super type of the configuration class generated by the annotation processor.
 *
 * @author Vincent Cantin
 */
public interface AbstractConfiguration {
  public Map<Class<? extends RemoteService>, Class<? extends Proxy>> getRemoteServiceClassToProxyClass();
  public Decoder getDecoder();
}
