package com.lemoulinstudio.small.jse;

import com.lemoulinstudio.small.common.Local;
import java.io.DataInputStream;
import java.io.IOException;

/**
 * The super type of the decoder class generated by the annotation processor.
 *
 * @author Vincent Cantin
 */
public interface Decoder<T extends Local> {
  public void decodeAndInvoke(SmallSessionImpl smallSession, T target, DataInputStream inputStream) throws IOException;
}
